import { Link } from 'react-router-dom'
import { useGame } from '../../state/GameContext'
import { buildDefencePlanData, isDefencePlanUnlocked, defencePlanUnlockRequirements } from '../../lib/defencePlan'
import Panel from '../shared/Panel'

function formatDate(iso) {
  return new Date(iso).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })
}

export default function DefencePlan() {
  const { state } = useGame()

  if (!isDefencePlanUnlocked(state)) {
    const requirements = defencePlanUnlockRequirements(state)
    return (
      <div className="max-w-xl mx-auto flex flex-col gap-4">
        <Panel className="text-center flex flex-col gap-2">
          <h1 className="text-xl font-bold mt-0 flex items-center justify-center gap-2">
            <span aria-hidden="true">🔒</span> Defence Plan locked
          </h1>
          <p className="text-sm text-[var(--cc-text-dim)] m-0">
            Your Defence Plan pulls real results from Digital Breadcrumbs and Recovery Rush — finish these first:
          </p>
          <ul className="list-none p-0 m-0 flex flex-col gap-1 text-sm text-left mt-2">
            {requirements.map((r) => (
              <li key={r.label} className="flex items-center gap-2">
                <span aria-hidden="true">{r.done ? '✅' : '⬜'}</span> {r.label}
              </li>
            ))}
          </ul>
        </Panel>
        <Link to="/dashboard" className="self-center no-underline px-5 py-2.5 rounded-lg bg-[var(--cc-accent)] text-[#06111c] font-semibold min-h-11 flex items-center">
          Back to dashboard
        </Link>
      </div>
    )
  }

  const plan = buildDefencePlanData(state)

  return (
    <div className="max-w-2xl mx-auto flex flex-col gap-4">
      <div className="no-print flex items-center justify-between flex-wrap gap-3">
        <Link to="/dashboard" className="no-underline text-sm text-[var(--cc-text-dim)]">
          ← Back to dashboard
        </Link>
        <button
          onClick={() => window.print()}
          className="px-4 py-2.5 rounded-lg bg-[var(--cc-accent)] text-[#06111c] font-semibold min-h-11 text-sm"
        >
          🖨️ Print / Save as PDF
        </button>
      </div>

      <article className="cc-defence-plan flex flex-col gap-5">
        <header>
          <h1 className="text-2xl font-bold mb-1">Your Personal Defence Plan</h1>
          <p className="text-sm text-[var(--cc-text-dim)] m-0">
            Generated by CyberCity on {formatDate(plan.generatedAt)} — built entirely from your own results, for use
            outside the game.
          </p>
        </header>

        <Panel>
          <h2 className="text-base font-semibold mt-0 mb-2">Privacy Defence Score</h2>
          <p className="cc-chrome text-3xl font-bold m-0" style={{ color: 'var(--cc-accent)' }}>
            {plan.privacyDefenceScore} / 100
          </p>
          <dl className="grid grid-cols-2 gap-y-1 gap-x-4 text-sm mt-3 m-0">
            <dt className="text-[var(--cc-text-dim)]">Strongest area</dt>
            <dd className="m-0">{plan.strongestArea ?? '—'}</dd>
            <dt className="text-[var(--cc-text-dim)]">Biggest exposure</dt>
            <dd className="m-0">{plan.biggestExposure ?? '—'}</dd>
          </dl>
        </Panel>

        <Panel>
          <h2 className="text-base font-semibold mt-0 mb-2">Your prioritized action list</h2>
          {plan.prioritizedActions.length === 0 ? (
            <p className="text-sm text-[var(--cc-good)] m-0">✅ You've completed every privacy action in this list.</p>
          ) : (
            <ol className="list-decimal pl-5 m-0 flex flex-col gap-2 text-sm">
              {plan.prioritizedActions.map((a) => (
                <li key={a.title}>
                  <strong>{a.title}</strong> — {a.description}
                </li>
              ))}
            </ol>
          )}
        </Panel>

        <Panel>
          <h2 className="text-base font-semibold mt-0 mb-2">Your RecoveryMap — account dependency summary</h2>
          <p className="text-xs text-[var(--cc-text-dim)] mt-0 mb-3">
            From the {plan.scenariosCompleted} of {plan.scenariosAvailable} Recovery Rush scenario(s) you've run.
          </p>
          <div className="flex flex-col gap-4">
            {plan.recoveryMap.map((r) => (
              <div key={r.levelName}>
                <p className="font-semibold m-0">{r.levelName}</p>
                <p className="text-sm text-[var(--cc-text-dim)] m-0 mb-1">
                  Result: {r.score}/100 ({r.grade}) — {r.accountsLost} account(s) fully lost
                </p>
                <p className="text-sm m-0 mb-1">
                  If <strong>{r.rootAccount}</strong> is compromised, these accounts are exposed through it:
                </p>
                <ul className="list-disc pl-5 m-0 text-sm">
                  {r.dependentAccounts.map((d) => (
                    <li key={d.label}>
                      <strong>{d.label}</strong> — {d.reason}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </Panel>

        <p className="text-xs text-[var(--cc-text-dim)] m-0">
          Real-world tip: apply this same logic to your actual accounts — identify which account is your "root"
          recovery method (usually your primary email), and secure that one first if anything ever looks wrong.
        </p>
      </article>
    </div>
  )
}
